apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications-management
  namespace: kube-controller
spec:
  destination:
    namespace: kube-controller
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-applications
    repoURL: git@github.com:kieunguyenql/helm-charts.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true