apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: kube-controller
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kube-prometheus-stack-45.6.0
    repoURL: https://github.com/kieunguyenql/helm-charts
    targetRevision: main