apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: kube-controller
spec:
  destination:
    namespace: kube-controller
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kube-prometheus-stack-45.6.0
    repoURL: git@github.com:kieunguyenql/helm-charts.git
    targetRevision: main