apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-key
  namespace: kube-controller
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:kieunguyenql/helm-charts.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----